version: 0.3
  
plan:
  steps:
    - type: command
      name: 检出代码前
      args:
        - pwd
        - echo "==========hello cloudiac=============="

    - type: checkout
      name: 检出代码

    - type: command
      name: 检出代码后
      args:
        - pwd
        - echo "==========checkout code=============="
      
    - type: terraformInit
      name: 初始化

    - type: command
      name: 平台变量
      args:
        - echo "CLOUDIAC_ORG_ID:" ${CLOUDIAC_ORG_ID}
        - echo "CLOUDIAC_PROJECT_ID:" ${CLOUDIAC_PROJECT_ID}
        - echo "CLOUDIAC_TEMPLATE_ID:" ${CLOUDIAC_TEMPLATE_ID}
        - echo "CLOUDIAC_ENV_ID:" ${CLOUDIAC_ENV_ID}
        - echo "CLOUDIAC_ENV_NAME:" ${CLOUDIAC_ENV_NAME}
        - echo "CLOUDIAC_ENV_STATUS:" ${CLOUDIAC_ENV_STATUS}
        - echo "CLOUDIAC_ENV_RESOURCES:" ${CLOUDIAC_ENV_RESOURCES}
        - echo "CLOUDIAC_COMMIT:" ${CLOUDIAC_COMMIT}
        - echo "CLOUDIAC_BRANCH:" ${CLOUDIAC_BRANCH}
        - echo "CLOUDIAC_TASK_ID:" ${CLOUDIAC_TASK_ID}
        - echo "CLOUDIAC_TF_VERSION:" ${CLOUDIAC_TF_VERSION}
    
    - type: terraformPlan
      name: 预览计划


apply:
  onSuccess:
    type: command
    args:
      - echo "Job successful"
      
  onFail:
    type: command
    args:
      - echo "Job failed"
      
  steps:
    - type: command
      args:
        - echo "get somethings"
        - bash script.sh
        - curl 127.0.0.1/api/action
        
    - type: checkout
      name: Checkout code
      
    - type: terraformInit
      name: Terraform Init
    
    - type: terraformPlan
      name: Terraform Plan
    
    - type: terraformApply
      name: Terraform Apply
      
    - type: ansiblePlay
      name: Run playbook
      
destroy:
  steps:
    - type: checkout
      name: Checkout code
      
    - type: terraformInit
      name: Terraform Init
    
    - type: terraformPlan
      name: Terraform Plan
      args: 
        - destroy
    - type: terraformDestroy
      name: Terraform Destroy
    
    - type: command
      name: Say Bye
      args: 
         - 'echo "Bye!"'

scan:
  steps:
    - type: scaninit
    - type: tfscan


parse:
  steps:
    - type: scaninit
    - type: tfparse
